import type { Metadata } from 'next';
import './globals.css';
import LetterGlitch from '@/blocks/Backgrounds/LetterGlitch/LetterGlitch';
import Squares from '@/blocks/Backgrounds/Squares/Squares';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased bg-black'>
        <Squares
          speed={0.5}
          squareSize={40}
          direction='diagonal'
          hoverFillColor='#222'
        />
        <div className='relative'>{children}</div>
      </body>
    </html>
  );
}
